### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ironhee** [ironhee/ironpt#2]
- [ ] Enhance documentation
  - [x] Implement documentation web site
  - [ ] Custom style guide
  - [x] step-by-step tutorial
  - [ ] Create more examples
- [ ] Implement Export Feature 
  - [ ] pdf
  - [ ] md
- [ ] Check browser coverage with e2e test.
- [x] Fix Dimension issues
- [ ] Implement Animations
  - [ ] Show
  - [ ] Hide
- [ ] Implement Elements
  - [ ] Quotes
  - [ ] Controllers
  - [ ] Speaker view
